on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.11.9]
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rembgui
          environment-file: ./environment.yml
          python-version: ${{ matrix.python-version }}
      - run: pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
      - run: |
          conda info
          conda list
      - name: bundle 
        run:  |
          $env:OUT_DIR = ".\bundled"
          ./bundler/usePyinstaller.ps1
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: .\bundled\dist
          overwrite: true

